name: file_io_interface
description: Implementation of an IOInterface from abstract_io using files
version: 0.1.0
author: Anders Groeschel
homepage:
repository:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  path_provider: ^1.6.9

  abstract_io: ^0.1.0



